import type { Profile } from '../../services/models/index';

export const RecipeObject = [
  {
    id: 1,
    title: 'Recipe Card Title',
    description: 'Recipe short description will come here.',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'easy',
    category: 'dinner',
    ingredients: [
      { name: 'string', quantity: 2, unit: 'string' },
      { name: 'string', quantity: 3, unit: 'string' },
    ],
    instructions: [],
    tags: [],
    image: { url: '/documentation/design/pantry.png', alt: '' },
    owner: {
      name: 'Johnny',
      email: 'johnny@example.com',
      bio: '',
      banner: { url: '', alt: '' },
      avatar: { url: '', alt: '' },
      credits: 0,
      _count: {},
    } as Profile,
    comments: [],
    _count: {},
    created: new Date(),
    updated: new Date(),
  },
  {
    id: 2,
    title: 'Recipe Card Title',
    description: 'Recipe short description will come here.',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'medium',
    category: 'breakfast',
    ingredients: [
      { name: 'string', quantity: 2, unit: 'string' },
      { name: 'string', quantity: 3, unit: 'string' },
      { name: 'string', quantity: 4, unit: 'string' },
    ],
    instructions: [],
    tags: [],
    image: { url: '/documentation/design/homepage.png', alt: '' },
    owner: {
      name: 'Oda',
      email: 'oda@example.com',
      bio: '',
      banner: { url: '', alt: '' },
      avatar: { url: '', alt: '' },
      credits: 0,
      _count: {},
    } as Profile,
    comments: [],
    _count: {},
    created: new Date(),
    updated: new Date(),
  },
  {
    id: 3,
    title: 'Recipe Card Title Number 3 with a very long Title',
    description: 'Recipe short description will come here.',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'hard',
    category: 'lunch',
    ingredients: [
      { name: 'string', quantity: 1, unit: 'string' },
      { name: 'string', quantity: 3, unit: 'string' },
      { name: 'string', quantity: 4, unit: 'string' },
    ],
    instructions: [],
    tags: [],
    image: { url: '/documentation/design/my-recipes-populated.png', alt: '' },
    owner: {
      name: 'Jane',
      email: 'jane@example.com',
      bio: '',
      banner: { url: '', alt: '' },
      avatar: { url: '', alt: '' },
      credits: 0,
      _count: {},
    } as Profile,
    comments: [],
    _count: {},
    created: new Date(),
    updated: new Date(),
  },
];
