import type { Profile } from '../models';

// mock data for testing Pantry UI in absence of auth (user w/ pantry items)
export const pantryMock = {
  items: [
    {
      id: '1',
      name: 'Tomato',
      quantity: 1,
      unit: 'unit',
      category: 'frozen',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '2',
      name: 'Onion',
      quantity: 1,
      unit: 'unit',
      category: 'grain',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '3',
      name: 'Garlic',
      quantity: 1,
      unit: 'unit',
      category: 'produce',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '4',
      name: 'Carrot',
      quantity: 1,
      unit: 'unit',
      category: 'dairy',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '5',
      name: 'Potato',
      quantity: 1,
      unit: 'unit',
      category: 'protein',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '6',
      name: 'Cumin',
      quantity: 1,
      unit: 'tbsp',
      category: 'spice',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '7',
      name: 'sauce',
      quantity: 1,
      unit: 'g',
      category: 'condiment',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '8',
      name: 'Meat',
      quantity: 1,
      unit: 'g',
      category: 'produce',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '9',
      name: 'special sauce',
      quantity: 1,
      unit: 'g',
      category: 'condiment',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
    {
      id: '10',
      name: 'Cherries',
      quantity: 1,
      unit: 'g',
      category: 'frozen',
      owner: {
        name: 'Tele',
        email: 'tele2@stud.noroff.no',
        bio: '',
        banner: { url: '', alt: '' },
        avatar: { url: '', alt: '' },
        credits: 0,
        _count: {},
      } as Profile,
      created: new Date(),
      updated: new Date(),
    },
  ],
};
